import type { Metadata } from 'next'
import './globals.css'
import Header from '@/componnents/header'



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>
          utbc Bibiliotheque
        </title>
      </head>
      <body className='bg-gray-900 text-gray-50'>
        <Header/>        
        <div className="p-4">
          {children}
        </div>
      </body>
    </html>
  )
}
